cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  config:
    domain: 35.228.195.195.nip.io
    exposer: Ingress
    http: "true"
jenkins:
  Servers:
    Global:
      EnvVars:
        TILLER_NAMESPACE: kube-system
        
global:
  keycloak:
    url: "http://activiti-keycloak.jx-staging.35.228.195.195.nip.io/auth"
  gateway:
    host: "activiti-cloud-gateway.jx-staging.35.228.195.195.nip.io"
